### ISSUE TITLE
[BUG] Broken URLs and missing DOI in Notebook ROs

### ISSUE THREAD

**Issue by acocac** [eds-book/eds-book#122]
## Describe the bug

Research objects of listed notebooks below are pointing to old URLs.

- [x] Detecting floating objects using deep learning and Sentinel-2 imagery 
- [x] Met Office UKV high-resolution atmosphere model data
- [x] MODIS MOD021KM and FIRMS 
- [x] Tree crown detection using DeepForest
- [x] SEVIRI Level 1.5 
- [x] Tree crown delineation using detectreeRGB
- [x] Sea ice forecasting using IceNet
- [x] Cosmos-UK soil moisture
- [x] Concatenating a gridded rainfall reanalysis dataset into a time series 
- [x] Exploring Land Cover Data (Impact Observatory)

## How To Reproduce

1. Go to RoHub 
2. Open URLs in the tool folder
3. Broken website

## Expected behaviour

Open a working URL

## Environment (generate for Linux, macOS and 64-bit Windows)

N/A. Browser.

## Additional information

Additional checks include:
- Set main entity as Jupyter Notebook
- Set publisher and copyright to EDS book community
- Associate a community, in this case EDS book community
- Approximate to 100% completeness
- Assign a DOI (snapshop) using Zenodo

**Comment by acocac** [comment]
All notebooks have working URLs and additional checks ok, except completeness.

**Comment by camappel** [comment]
Are the notebook repository urls still up-to-date? For instance, the [raw files](https://raw.githubusercontent.com/eds-book-gallery/15d986da-2d7c-44fb-af71-700494485def/main/.lock/conda-osx-64.lock) for the DeepForest notebook returns a 400 error. Likewise, the EDS [gallery](https://github.com/eds-book-gallery/15d986da-2d7c-44fb-af71-700494485def/blob/920606a1bd4208f62ef49ebf08aa4727b489b91e/notebook.ipynb) only contains the .ipynb, not the lock files (as stated [here](https://github.com/alan-turing-institute/environmental-ds-book/blob/master/book/notebooks/how-to.md)).

I set up the environment manually, but I believe this is resulting in the xarray package not loading correctly.

**Comment by acocac** [comment]
@camappel - thanks for reporting the issue. I've opened a new issue to address it. 

The notebook repository contains a single [conda lock file](https://github.com/eds-book-gallery/15d986da-2d7c-44fb-af71-700494485def/blob/main/.lock/conda-lock.yml) which is compatible with the version 2.x of [conda-lock](https://github.com/conda/conda-lock). The documentation in the "How to use EDS book notebooks" section uses an older version of conda-lock which creates a separate file per operating system. I hope this makes sense.

**Comment by camappel** [comment]
Got it, thanks - I'll try to recreate the environment using the single lock file.

**Comment by acocac** [comment]
> Got it, thanks - I'll try to recreate the environment using the single lock file.

Cool - Please feel free to open new issues if you have any while using the single lock file or any other process exploring the gallery of EDS book notebooks. Thank you!
