### ISSUE TITLE
[DOC] Proposal for an updated EDS book logo

### ISSUE THREAD

**Issue by acocac** [eds-book/eds-book#125]
## Describe the proposed improvement to the documentation

Hi folks! 

Additional to my WIP #117  aimed at improving guidelines and documentation of the EDS book, I’m excited to share recent developments in our branding 🎨 . I would like to propose a new intentionally designed logo for the EDS book. 

The current logo (please see it below) only reflects the digitalisation of the planet earth, in this case represented by three consecutive icons: the natural earth (left), binary code referring to the means i.e. data, code, software, etc (mid) and digital earth (right). 

<p align="center">
<img src='https://user-images.githubusercontent.com/13321552/218591155-a8168a35-20b2-41e0-b186-43b799681b6b.png' width='300'>
</p>

The updated logo builds upon the original one, but highlighting new components:
- People network icons at the start and end of EDS initials indicating an *end-to-end community-driven goal* i.e. improving scientific software and data management practises through the publication of FAIR peer-reviewed computational notebooks.
- Rope knots (proposal 1) or plugs (proposal 2) connecting all capital letters referring to a *healthy and strong collaboration*. 
- Lettermark-oriented. The original logo missed the name. The proposed versions comprise the initials to make it *easy to remember and recognise*.

Here's a comparison of two variants of the proposed logo (feel free to vote :dog: or :cat:):

Rope knot  (:dog:)           |  Plugs (:cat:)
:-------------------------:|:-------------------------:
  <img src="https://user-images.githubusercontent.com/13321552/218600012-8b875e13-6b48-4bc1-a796-6f928299e9e3.png" width="300" />  |    <img src="https://user-images.githubusercontent.com/13321552/218600138-36965730-8c42-492e-9411-b3109042fd73.png" width="300" />

## Who can help?
Thoughts from the EDS book community and friends are welcome. I'm completely open to playing around with:
- the final colours (is a B&W version ok?)
- whether or not to have a "binary code" icon.
- whether or not to have a "rope knots” or “plugs”
- whether or not to have a “people network icons”

Feel free to tag anyone who might be interested. I’m aiming to release the new logo with the updated documentation in **March**. 

I also attach PDF versions of both logo variants which include some variations for stickers or social networks.

## Additional information 

I initially designed the proposed logo in MS Powerpoint using the default gallery of icons which are free to use with [no copyright](https://support.microsoft.com/en-us/office/insert-icons-in-microsoft-365-e2459f17-3996-4795-996e-b9a13486fa79).

Thanks to @aleesteele, I recently learnt about [penpot](https://penpot.app/), a great open-source design prototyping tool. If you’re familiar with the tool or want to try your graphic designer skills, I can provide access to the EDS book penpot project group.

**Comment by acocac** [comment]
Shamelessly tagging some folks @scotthosking @annefou @edwardchalstrey1 @NHomer-Edi @timo0thy @malvikasharan @KirstieJane for comment on this!

**Comment by acocac** [comment]
Temptative vote here :dog: or :cat:

**Comment by malvikasharan** [comment]
Ooh these look great. 😍 Let me think a bit and come back to this during our collaboration cafe this week.

**Comment by edwardchalstrey1** [comment]
A minor suggestion you can feel free to ignore, but maybe there's a way to include the full words like below (but better)

![Screenshot 2023-02-14 at 09 18 07](https://user-images.githubusercontent.com/5486164/218692161-2b8daeed-3b90-469c-9568-4cb1afd1d925.png)

**Comment by acocac** [comment]
@edwardchalstrey1 thanks for the quick reply and ideas. I forgot to include PDF files of both variants which include the name below the logo!! Please see them below.

**Comment by acocac** [comment]
**PDF versions of both logo variants:**

[Variant 1 - 🐶](https://github.com/alan-turing-institute/environmental-ds-book/files/10730825/logo-proposal1-rope.pdf)
[Variant 2 - 🐱](https://github.com/alan-turing-institute/environmental-ds-book/files/10730824/logo-proposal2-plugin.pdf)

**Comment by tinaok** [comment]
> Temptative vote here 🐶 or 🐱

I like Rope knot 🐶

**Comment by timo0thy** [comment]
Both look terrific but I am slightly in favour of 🐱 - having in mind that (apart from the obvious meaning) the EDS Book also serves as a 'plug' to promote good coding practices!

And by the way another small comment that is ignorable - just wondering if there's any possibility that the characters 'E''D''S' could be stuck a little bit closer together?

Anyway, that's really some great work @acocac !

**Comment by NHomer-Edi** [comment]
The Plugs (🐱) get my vote!

**Comment by acocac** [comment]
Thanks @edwardchalstrey1 @tinaok @timo0thy @NHomer-Edi for your valuable thoughts and vote. I'll wait for others feedback and update everyone soon!
So far, we have a draw, 🐶  (2) and 🐱  (2)

**Comment by acocac** [comment]
👋  @edwardchalstrey1 @tinaok @timo0thy @NHomer-Edi @malvikasharan @annefou @scotthosking  thanks for all your valuable inputs. Please find below the final version of EDS book logo. We hope to have a professional designer to improve it. 

A recap of my main points:
- the final colours (is a B&W version ok?) > no comments, but B&W seems to look ok.
- whether or not to have a "binary code" icon > no comments. It think it's ok to maintain the same icons of the first logo. This also includes the Earth logo, which I initially replaced by a more abstracted version, however the icon refers to the Firefox browser. 
- whether or not to have a "rope knots” or “plugs” > plugs seems to reflect the modularity of Jupyter notebooks. Ropes were proposed to reflect the community aspects, however this seems to be explicit with people network icons
- whether or not to have a “people network icons” > no comments

Logo           |  Logo with Name |  Sticker
:-------------------------:|:-------------------------:|:-------------------------:
  <img src="https://user-images.githubusercontent.com/13321552/223472043-abf93e64-b06e-4f4a-b772-18f5cf3e01a4.png" width="300" />  |    <img src="https://user-images.githubusercontent.com/13321552/223472192-7ce3324e-99de-4fbe-955a-5e4e68abba7c.png" width="300" />  |    <img src="https://user-images.githubusercontent.com/13321552/223551081-1e18742b-ced1-4d15-b6f0-c48d07421912.png" width="300" />
