### ISSUE TITLE
[ENH] Add "click to show" functionality for code

### ISSUE THREAD

**Issue by edwardchalstrey1** [eds-book/eds-book#17]
## Feature Request

In other gitbooks such as [this course](https://alan-turing-institute.github.io/rds-course/modules/m3/3.2-RulesOfTheGame.html) 
 (see [course repo](https://github.com/alan-turing-institute/rds-course)) there are "Click to show" buttons for code which make the pages tidier as code is hidden by default.

This would be a nice feature for the environmental AI book to implement.

**Comment by acocac** [comment]
@edwardchalstrey1 Thanks for the feature request. I've implemented the `hidden-input ` tag in all executable notebooks (see for instance [this one](https://the-environmental-ds-book.netlify.app/wildfires/sensors/wildfires-sensors-fires_modis.html) with interactive plotting and pandas data.frames).
