### ISSUE TITLE
Contribution and authorship: Does the author list seem appropriate and complete (full name, affiliation, and GitHub/ORCID handle)?

### ISSUE THREAD

**Issue by ricardobarroslourenco** [eds-book/eds-book#179]
Two notebook co-authors have not listed their ORCID. Is this a mandatory requirement @acocac ?

**Comment by acocac** [comment]
> Two notebook co-authors have not listed their ORCID. Is this a mandatory requirement @acocac ?

Hi @ricardobarroslourenco, thanks for asking. ORCID isn't a mandatory field.

**Comment by ricardobarroslourenco** [comment]
I see. Closing and accepting here then.
