### ISSUE TITLE
Does the notebook build and run in binder?

### ISSUE THREAD

**Issue by ricardobarroslourenco** [eds-book/eds-book#180]
It does build the binder container, however, it does not complete the run due to a kernel restart (likely due to OOM error). The kernel restarted while trying to run cell 6.

**Comment by ricardobarroslourenco** [comment]
Binder was run as this (note: if decided to keep running on binder, it would be good to include the markdown button on the notebook and/or the main documentation):

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/eds-book-gallery/repro-challenge-team-3/main?labpath=%2Fnotebooks%2Fnotebook.ipynb)

Code of the button:

```
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/eds-book-gallery/repro-challenge-team-3/main?labpath=%2Fnotebooks%2Fnotebook.ipynb)
```

**Comment by ricardobarroslourenco** [comment]
@acocac were you able to run on Binder? 

~I also tried to run in a separate HPC environment, but it is taking a long time to run (and almost without having CPU utilization). I wonder if the routine consumes many resources from the internet, and as I am running in an isolated cluster, it halts.~

**Comment by ricardobarroslourenco** [comment]
I just made it work on an HPC node, and I think that Binder is crashing due to RAM issues. My node used 10GB of RAM during processing and I wonder if that is what may be causing the Binder environment to restart the kernel.

**Comment by acocac** [comment]
> [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.

Thanks for generating the badge. fyi, we provide the link to binder within the [Review PR](https://github.com/eds-book-gallery/repro-challenge-team-3/pulls)

**Comment by acocac** [comment]
> I just made it work on an HPC node, and I think that Binder is crashing due to RAM issues. My node used 10GB of RAM during processing and I wonder if that is what may be causing the Binder environment to restart the kernel.

I think the kernel restarts because inactivity... the cell for downloading the large dataset takes ~1h so it could explain it too.

Btw, I'm moving your comments as a new issue tab in the notebook repository. Closing this one then.
