### ISSUE TITLE
Does the notebook build and run in binder?

### ISSUE THREAD

**Issue by ricardobarroslourenco** [eds-book/eds-book#181]

**Comment by acocac** [comment]
It seems the documentation or guidelines for reviewers are still confusing. Can you confirm it @ricardobarroslourenco? You should crossreference specific issues in the notebook repository instead of EDS book one.

**Comment by ricardobarroslourenco** [comment]
@acocac I think that I may have got confused. While doing the checklist in the review, it does have a button that opens an issue for every item (I understood that it was supposed to click it for the items that needed review - which also kept a link to the main review process).

**Comment by acocac** [comment]
> @acocac I think that I may have got confused. While doing the checklist in the review, it does have a button that opens an issue for every item (I understood that it was supposed to click it for the items that needed review - which also kept a link to the main review process).

Hi, thanks for reporting it! This is a new functionality in GitHub that I wasn't familiar with. I'll update the guidelines and see how we can maximize the functionality.

**Comment by acocac** [comment]
Closing this issue. We'll consider to update EDS book guidelines with the GitHub functionality of checklists.
