### ISSUE TITLE
[DOC] Fix notebook Idea preview link

### ISSUE THREAD

**Issue by bnubald** [eds-book/eds-book#222]
## Describe the proposed improvement to the documentation

Just saw a possible copy-paste bug - the link to the Notebook Idea issue preview is pointing to the Documentation improvement preview.

https://github.com/alan-turing-institute/environmental-ds-book/blob/88d1457d9c521bb9b6271095f355f437b6e34e16/CONTRIBUTING.md?plain=1#L99

Should be updated to:

```
https://github.com/alan-turing-institute/environmental-ds-book/issues/new?assignees=&labels=notebook&projects=&template=notebook-request.md&title=%5BNBI%5D
```

**Comment by acocac** [comment]
Good catching - thank you!
