### ISSUE TITLE
[ENH] Extend functionality of tree crown detection using DeepForest

### ISSUE THREAD

**Issue by camappel** [eds-book/eds-book#249]
## Feature Request

Extend functionality of [Tree crown (DeepForest)](https://edsbook.org/notebooks/gallery/15d986da-2d7c-44fb-af71-700494485def/notebook#)

## Describe the solution you'd like

Preprocessing:
- [ ] Create RGB orthomosaic using low-cost drones
- [ ] Annotate tree crowns using [labelImg](https://pypi.org/project/labelImg/)

Training:
- [ ] Improve accuracy of predictions by [training](https://deepforest.readthedocs.io/en/latest/training.html#) DeepForest model using annotated self-produced orthomosaics

Multi-class object detection model:
- [ ] [The CropModel: Classifying objects after object detection](https://deepforest.readthedocs.io/en/latest/CropModel.html#) using model-chaining

**Comment by acocac** [comment]
@camappel - thanks for opening the feature request. 

The idea to include a new image source with the latest version of DeepForest sounds great! 

I encourage you to visit the [guidelines for authors](https://edsbook.org/publishing/guidelines/guidelines-authors) which might be helpful to consider a new notebook with the suggested features. 

You're welcome to lead/contribute with the new notebook 🙏

**Comment by camappel** [comment]
Raised as NBI alan-turing-institute/eds-ideas-transfer#4. Happy for this issue to be closed
