### ISSUE TITLE
[DOC] Permanent closure of the X account

### ISSUE THREAD

**Issue by acocac** [eds-book/eds-book#261]
## Describe the proposed improvement to the documentation

EDS book has had a reduced activity in X in the past months. With plenty of controversial changes in the platform, X doesn't longer provide a consistent and safe digital space to promote shared values of the open movement.

The closure date is Friday 8th November after ensuring a safe backup of the account data and complete removal of the account of the platform. The key steps are:

- [x] Post a bye-bye message indicating the permanent closure of the account.
- [x] #267
- [x] Download an archive of the account data (verify no personal/third-party information is included).

## Additional information 

Alternative channels where we'll communicate activities are:
- Mastodon (opened in Nov 2023, 38 followers): https://fosstodon.org/@eds_book
- LinkedIn (opened in Nov 2024, 0 followers): https://www.linkedin.com/groups/13116833/

**Comment by acocac** [comment]
fyi @annefou @malvikasharan I'm about closing the X account of EDS book. It's been in my scope a long time ago. Your thoughts would be welcome!

**Comment by annefou** [comment]
I fully agree with your choice! Thanks.

**Comment by ricardobarroslourenco** [comment]
Only a suggestion. Can you provide a bridge to BlueSky? (ex.: https://fed.brid.gy ). X is in a sharp decline indeed (in every assertion of the word).

**Comment by ricardobarroslourenco** [comment]
> * https://www.linkedin.com/company/eds-book/

Once you do a first post on LinkedIn, let me know, and we reshare through the EDS account :)

**Comment by acocac** [comment]
> Only a suggestion. Can you provide a bridge to BlueSky? (ex.: https://fed.brid.gy ). X is in a sharp decline indeed (in every assertion of the word).

@ricardobarroslourenco - thanks for jumping into the conversation! We have a EDS book co-working session this Friday (please refer to [the calendar](https://calendar.google.com/calendar/u/0/embed?src=environmental.ds.book@gmail.com) so I'll make sure to explore with others the suggestion.

**Comment by ricardobarroslourenco** [comment]
Hi @acocac ! Unfortunately I will not be able to make it (I have to TA at this time). However, the Fed Bridgy is quite straightforward (just following the bot account on mastodon, and voilá, it becomes visible in BlueSky). Strongly recommend it.

**Comment by acocac** [comment]
Another option in LinkedIn (groups) suggested by @camappel, https://www.linkedin.com/groups/

**Comment by acocac** [comment]
Tasks completed.
