### ISSUE TITLE
[DOC] Writing style guide for contributors

### ISSUE THREAD

**Issue by NHomer-Edi** [eds-book/eds-book#68]
## Describe the proposed improvement to the documentation

So that the book remains consistent, it would be nice to have a "style guide" included in the contributor documentation so that contributors know how to write narrative pieces for the book. 

For example, I notice some inconsistencies between the use of “Deep Learning” & “deep learning” and “Environmental data science” & “Environmental Data Science” and "AI" & "Artificial Intelligence"

## Additional information 

Other things this could include:
•	Rules on capitalisation.
•	A list of accepted abbreviations and acronyms which will be at the beginning/end of the book so that they do not need to be defined by every contributor.  
•	Number formatting like time and date and “%” vs. “per cent”.
•	Punctuation guidelines.
•	Formatting guidelines including bold/italic/underline and links

**Comment by acocac** [comment]
@NHomer-Edi thanks for the suggestion of a writing style guide! This is a great idea which we can implement as a new section within the Publishing guidelines. 

I'll create a pull request linked to the issue so we can work together in the proposed section.

fyi, I'm also planning to have a discussion of a new version of the EnvDS book which will integrate the dashboard idea and a more friendly gallery for the executable notebooks. Let's discuss it in my return (:

**Comment by acocac** [comment]
Closing as we've considerably improved the guidelines for authors, including a more friendly gallery, see #126
